### ISSUE TITLE
RemovedInPytest4Warning: MarkInfo objects Deprecation warnings by pytest

### ISSUE THREAD

**Issue by nareshnayini** [nicoulaj/pytest-csv#3]
We are using pytest-csv in our project. Recently, we started getting huge number of deprecation warnings by pytest referring code in pytest-csv. Can you please look into this.

Log from Travis:
`/home/travis/build/Getsidecar/connect-api/pyenv/lib/python3.6/site-packages/pytest_csv/column/_builtin.py:110: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  for mark in sorted(getattr(report, 'test_markers', []), key=lambda mark: mark.name))
/home/travis/build/Getsidecar/connect-api/pyenv/lib/python3.6/site-packages/pytest_csv/column/_utils.py:39: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  return mark.name`

**Comment by nicoulaj** [comment]
it should be fixed in 1.1.2

**Comment by nareshnayini** [comment]
Thats great, thank you for the quick response.
